CREATE DATABASE test_db;

CREATE TABLE [dbo].[MstHaisoChukei] (
    [HaisoChukeiId] int,
    [HaisoChukeiCd] nvarchar(4),
    [HaisoChukeiName] nvarchar(50),
    [UnsoId] int,
    [IsSogoShukaCheck] bit,
    [Biko] nvarchar(50),
    [StatusId] int,
    [InsertShainId] int,
    [InsertFormName] nvarchar(50),
    [InsertDateTime] datetime,
    [UpdateShainId] int,
    [UpdateFormName] nvarchar(50),
    [UpdateDateTime] datetime,
    [MailAddress] nvarchar(255),
    [Telephone] nvarchar(15),
    [TantoshaSei] nvarchar(10),
    [TantoshaMei] nvarchar(10),
    [TantoshaSeiKana] nvarchar(20),
    [TantoshaMeiKana] nvarchar(20),
    PRIMARY KEY ([HaisoChukeiId])
);

CREATE TABLE [dbo].[MstKantoku] (
    [KantokuId] int,
    [TorihikiId] nvarchar(5),
    [KantokuCd] nvarchar(4),
    [KantokuSei] nvarchar(10),
    [KantokuMei] nvarchar(10),
    [KantokuSeiKana] nvarchar(20),
    [KantokuMeiKana] nvarchar(20),
    [Telephone] nvarchar(15),
    [Biko] nvarchar(200),
    [StatusId] int,
    [InsertShainId] int,
    [InsertFormName] nvarchar(50),
    [InsertDateTime] datetime,
    [UpdateShainId] int,
    [UpdateFormName] nvarchar(50),
    [UpdateDateTime] datetime,
    [MailAddress] nvarchar(256),
    PRIMARY KEY ([KantokuId])
);

CREATE TABLE [dbo].[MstKojo] (
    [KojoId] int,
    [KojoCd] nchar(4),
    [KojoName] nvarchar(30),
    [KojoNameKana] nvarchar(30),
    [KojoNameRyaku] nvarchar(10),
    [YubinNo] nvarchar(8),
    [Address1] nvarchar(30),
    [Address2] nvarchar(30),
    [Telephone] nvarchar(15),
    [FaxNo] nvarchar(15),
    [IsKouzo] bit,
    [IsHagara] bit,
    [IsSakuzu] bit,
    [IsSozaiGaichu] bit,
    [IsYarikatazaiIraiSaki] bit,
    [IsJisha] bit,
    [IsKogaisha] bit,
    [IsChinKako] bit,
    [IsTuikazai] bit,
    [IsNohinsho] bit,
    [TorihikiId] int,
    [GyosyaId] int,
    [StatusId] int,
    [Biko] nvarchar(50),
    [InsertShainId] int,
    [InsertFormName] nvarchar(50),
    [InsertDateTime] datetime,
    [UpdateShainId] int,
    [UpdateFormName] nvarchar(50),
    [UpdateDateTime] datetime,
    [IsIDSGohan] bit,
    [IsPaper] bit,
    [MailAddress] varchar(516),
    [TantoshaSei] nvarchar(10) DEFAULT (''),
    [TantoshaMei] nvarchar(10) DEFAULT (''),
    [TantoshaSeiKana] nvarchar(20) DEFAULT (''),
    [TantoshaMeiKana] nvarchar(20) DEFAULT (''),
    [IsLVLNobuchi] bit DEFAULT ('0'),
    [IsIdhome] bit,
    [IsHajimekensetsu] bit,
    PRIMARY KEY ([KojoId])
);


CREATE TABLE [dbo].[MstMeisyo] (
    [MeisyoId] int,
    [BunruiCd] nvarchar(4),
    [MeisyoCd] nvarchar(3),
    [MeisyoName] nvarchar(50),
    [Orderby] numeric(3, 0),
    [Biko] nvarchar(100),
    [InsertShainId] int,
    [InsertFormName] nvarchar(50),
    [InsertDateTime] datetime,
    [UpdateShainId] int,
    [UpdateFormName] nvarchar(50),
    [UpdateDateTime] datetime,
    PRIMARY KEY ([MeisyoId])
);



CREATE TABLE [dbo].[MstTempo] (
    [TempoId] int,
    [TorihikiId] int,
    [TempoCd] nvarchar(3),
    [TempoName] nvarchar(40),
    [TempoNameKana] nvarchar(40),
    [TempoNameRyaku] nvarchar(10),
    [HaisoAreaId] int,
    [YubinNo] nvarchar(7),
    [Address] nvarchar(40),
    [Telephone] nvarchar(15),
    [FaxNo] nvarchar(15),
    [Biko] nvarchar(100),
    [IsKoujiten] bit,
    [IsEigyoten] bit,
    [StatusId] int,
    [InsertShainId] int,
    [InsertFormName] nvarchar(50),
    [InsertDateTime] datetime,
    [UpdateShainId] int,
    [UpdateFormName] nvarchar(50),
    [UpdateDateTime] datetime,
    [MailAddress] nvarchar(256),
    [TantoshaSei] nvarchar(10),
    [TantoshaMei] nvarchar(10),
    [TantoshaSeiKana] nvarchar(20),
    [TantoshaMeiKana] nvarchar(20),
    PRIMARY KEY ([TempoId])
);


CREATE TABLE [dbo].[MstTorihiki] (
    [TorihikiId] int,
    [TorihikiCd] nvarchar(4),
    [TorihikiName] nvarchar(20),
    [TorihikiNameKana] nvarchar(20),
    [SeikyuId] int,
    [IsSeikyusyoSofuAndMeisai] bit,
    [IsSeikyusyoOfTempo] bit,
    [IsSeikyusyoOfBuken] bit,
    [Biko] nvarchar(50),
    [StatusId] int,
    [IsBuilder] bit,
    [IsPowerBuilder] bit,
    [InsertShainId] int,
    [InsertFormName] nvarchar(50),
    [InsertDateTime] datetime,
    [UpdateShainId] int,
    [UpdateFormName] nvarchar(50),
    [UpdateDateTime] datetime,
    [IsTyumonUkeoi] bit,
    PRIMARY KEY ([TorihikiId])
);

CREATE TABLE [dbo].[TblBukenBasic] (
    [BukenBasicId] int ,
    [KoteiDetailId] int,
    [NobeyukaMenseki1] numeric(5, 2),
    [NobeyukaMenseki2] numeric(5, 2),
    [LowCostId] int,
    [PastelId] int,
    [SeinoHyojiId] int,
    [HModuleId] int,
    [ModuleNo] numeric(3, 0),
    [MenzaiId] int,
    [DocumentOutDateTime] datetime,
    [BukenPlanName] nvarchar(10),
    [BukenPlanNo] nvarchar(100),
    [IsNokiZero] bit,
    [ShiyoId] int,
    [HShiyoId] int,
    [KeitenId] int,
    [SozaiHyoId] int,
    [JShiyoId] int,
    [TShiyoId] int,
    [IShiyoId] int,
    [AShiyoId] int,
    [SeishinSujikaiId] int,
    [InsertShainId] int,
    [InsertFormName] nvarchar(50),
    [InsertDateTime] datetime,
    [UpdateShainId] int,
    [UpdateFormName] nvarchar(50),
    [UpdateDateTime] datetime,
    [NomonoId] int,
    [KoubaiNedaId] int,
    [IDShiyoId] int,
    [SekouId] int,
    [OShiyoId] int,
    [FShiyoId] int,
    [Remarks] nvarchar(100),
    PRIMARY KEY ([BukenBasicId])
);


CREATE TABLE [dbo].[TblKoteiDetail] (
    [DetailId] int,
    [HeaderId] int,
    [StatusId] int,
    [KoujiNo] nvarchar(12),
    [Goutou] nvarchar(3),
    [Kouzo] numeric(3, 0),
    [Nendo] numeric(4, 0),
    [BukenNo] nvarchar(8),
    [TepraPrintDate] date,
    [KantokuId] int,
    [KozoKojoId] int,
    [HagaraKojoId] int,
    [SakuzuKojoId] int,
    [YarikataZaiGaichuId] int,
    [SozaiGaichuId] int,
    [CadZumenDate] date,
    [ChakkoDate] date,
    [KouzoDate1Yotei] nvarchar(20),
    [KouzoDate1YoteiOld] nvarchar(20),
    [KouzoDate1] date,
    [KouzoDate2] date,
    [KouzoDate3] date,
    [HagaraDate] date,
    [ShukaKakuninDate] date,
    [SyoninDate] date,
    [KouzoKakoYoteiDate] date,
    [KouzoKakoDate] date,
    [HagaraKakoYoteiDate] date,
    [HagaraKakoDate] date,
    [SaishuKakuninDate] date,
    [Biko] nvarchar(400),
    [ShukaJotoYoteiDate] date,
    [ShukaJotoDate] date,
    [IsTyumonUkeoi] bit,
    [BukenKbnId] int,
    [InsertShainId] int,
    [InsertFormName] nvarchar(50),
    [InsertDateTime] datetime,
    [UpdateShainId] int,
    [UpdateFormName] nvarchar(50),
    [UpdateDateTime] datetime,
    [KohoId] int,
    [IsSakuzu] bit,
    [IsKako] bit,
    [IDSGohanKojoId] int,
    [IsKakuteiKouzoDate1] bit,
    [IDSKannoDate] date,
    [IDSKoteiBiko] nvarchar(100),
    [IDSOption] nvarchar(40),
    [IsIDSKanamonoHachu] bit,
    [IDSBiko] nvarchar(40),
    [IDSDannetuzaiHachu] nvarchar(20),
    [LVLNobuchiKojoId] int,
    [Bin1Date] date,
    [Bin1IsHagara] bit,
    [Bin2Date] date,
    [Bin2IsHagara] bit,
    [Bin3Date] date,
    [Bin3IsHagara] bit,
    [Bin4Date] date,
    [Bin4IsHagara] bit,
    [Bin5Date] date,
    [Bin5IsHagara] bit,
    [Bin6Date] date,
    [Bin6IsHagara] bit,
    [IsKanamonoHachu] bit,
    [KakoBiko] nvarchar(50),
    [BeforeChakkoDate1] date,
    [BeforeChakkoDate2] date,
    [IsKabePanel] bit,
    [DetailKbnId] int,
    [KabePanelKojoId] int,
    PRIMARY KEY ([DetailId])  
);

CREATE TABLE [dbo].[TblKoteiHeader] (
    [HeaderId] int,
    [TorihikiId] int,
    [GembaName] nvarchar(40),
    [GembaNameKana] nvarchar(60),
    [Tousu] numeric(3, 0),
    [KoujitenId] int,
    [SeikyuKoujitenId] int,
    [GembaAddress] nvarchar(50),
    [EigyotenId] int,
    [TodofukenCd] nvarchar(2),
    [HaisoAreaId] int,
    [HachuMotoId] int,
    [BukenKbn] nchar(1),
    [BukenKbnSonohoka] nvarchar(20),
    [InsertShainId] int,
    [InsertFormName] nvarchar(50),
    [InsertDateTime] datetime,
    [UpdateShainId] int,
    [UpdateFormName] nvarchar(50),
    [UpdateDateTime] datetime,
    [IsTyumonUkeoi] bit,
    PRIMARY KEY ([HeaderId])  
);

CREATE TABLE [dbo].[TblShukaGembaHanyu] (
    [ShukaGembaHanyuId] int,
    [KoteiDetailId] int,
    [IsKinkyu] bit,
    [HenkoKanoDate] date,
    [HenkoKanoTimed1] int,
    [HenkoKanoTimed2] int,
    [HenkoRiyu] nvarchar(512),
    [Bin1Date] date,
    [Bin1Timed1] int,
    [Bin1Timed2] int,
    [Bin1IsHagara] bit,
    [Bin1HanyuButu] nvarchar(64),
    [Bin1InitialPlanDate] date,
    [Bin2Date] date,
    [Bin2Timed1] int,
    [Bin2Timed2] int,
    [Bin2IsHagara] bit,
    [Bin2HenkoRiyu] nvarchar(512),
    [Bin2HanyuButu] nvarchar(64),
    [Bin2InitialPlanDate] date,
    [Bin3Date] date,
    [Bin3Timed1] int,
    [Bin3Timed2] int,
    [Bin3IsHagara] bit,
    [Bin3HenkoRiyu] nvarchar(512),
    [Bin3HanyuButu] nvarchar(64),
    [Bin3InitialPlanDate] date,
    [Bin4Date] date,
    [Bin4Timed1] int,
    [Bin4Timed2] int,
    [Bin4IsHagara] bit,
    [Bin4HenkoRiyu] nvarchar(512),
    [Bin4HanyuButu] nvarchar(64),
    [Bin4InitialPlanDate] date,
    [Bin5Date] date,
    [Bin5Timed1] int,
    [Bin5Timed2] int,
    [Bin5IsHagara] bit,
    [Bin5HenkoRiyu] nvarchar(512),
    [Bin5HanyuButu] nvarchar(64),
    [Bin5InitialPlanDate] date,
    [Bin6Date] date,
    [Bin6Timed1] int,
    [Bin6Timed2] int,
    [Bin6IsHagara] bit,
    [Bin6HenkoRiyu] nvarchar(512),
    [Bin6HanyuButu] nvarchar(64),
    [Bin6InitialPlanDate] date,
    [HanyuSharyoId] int,
    [JotoBinWreckerId] int,
    [Biko] nvarchar(1024),
    [AnnaiSasidasiNin] nvarchar(1024),
    [AnnaiBiko1] nvarchar(1024),
    [AnnaiBiko2] nvarchar(1024),
    [HenkoRireki] nvarchar(4000),
    [InsertShainId] int,
    [InsertFormName] nvarchar(50),
    [InsertDateTime] datetime,
    [UpdateShainId] int,
    [UpdateFormName] nvarchar(50),
    [UpdateDateTime] datetime,
    [LogiBiko] nvarchar(512),
    [GembaAnnaiId] int,
    [SharedLink] nvarchar(512),
    [FwSendMailId] int,
    [ChukeiSendMailId] int,
    [KojitenSendMailId] int,
    [GaichuSendMailId] int,
    [SozaiGaichuSendMailId] int,
    [KantokuSendMailId] int,
    [SharedLink2] nvarchar(512),
    [SharedLink3] nvarchar(512),
    [MailSokuho] bit,
    [TuikaBin] bit,
    [HaisoEnki] bit,
    PRIMARY KEY ([ShukaGembaHanyuId])  
);

CREATE TABLE [dbo].[TblShukaKanryoHeader] (
    [ShukaKanryoHeaderId] int,
    [ShukaYoteiId] int,
    [ChukeiId] int,
    [UnsoId] int,
    [IsMitei] bit,
    [KouzoStatusId1] int,
    [KouzoUnsoId1] int,
    [KouzoUnchin1] numeric(7, 0),
    [KouzoStatusId2] int,
    [KouzoUnsoId2] int,
    [KouzoUnchin2] numeric(7, 0),
    [HagaraStatusId] int,
    [HagaraShukaDate] date,
    [HagaraChukeiDate] date,
    [HagaraUnsoId] nchar(10),
    [HagaraUnchin] numeric(7, 0),
    [IsSeikyu] bit,
    [StatusId] int,
    [InsertShainId] int,
    [InsertFormName] nvarchar(50),
    [InsertDateTime] datetime,
    [UpdateShainId] int,
    [UpdateFormName] nvarchar(50),
    [UpdateDateTime] datetime,
    [IDSGohanShukaDate] date,
    [IDSGohanChukeiDate] date,
    PRIMARY KEY ([ShukaKanryoHeaderId])  
);

CREATE TABLE [dbo].[TblShukaYotei] (
    [ShukaYoteiId] int,
    [KoteiDetailId] int,
    [ChukeiId] int,
    [UnsoId] int,
    [IsHasiraShuka1] bit,
    [KouzoStatusId1] int,
    [KouzoShukaCarId1] int,
    [KouzoShukaDate1] date,
    [KouzoChukeiDate1] date,
    [IsFax] bit,
    [IsTel] bit,
    [IsHasiraShuka] bit,
    [IsHasiraShuka2] bit,
    [KouzoStatusId2] int,
    [KouzoShukaCarId2] int,
    [KouzoShukaDate2] date,
    [KouzoChukeiDate2] date,
    [HagaraStatusId] int,
    [HagaraShukaCarId] int,
    [HagaraShukaDate] date,
    [HagaraChukeiDate] date,
    [SozaiHikitoriYoteiDate] date,
    [SozaiHikitoriKanryoDate] date,
    [SozaiNohinKojoId] int,
    [SozaiTumikomiDate] date,
    [SozaiTumiorosiDate] date,
    [Biko] nvarchar(100),
    [IsComplete] bit,
    [InsertShainId] int,
    [InsertFormName] nvarchar(50),
    [InsertDateTime] datetime,
    [UpdateShainId] int,
    [UpdateFormName] nvarchar(50),
    [UpdateDateTime] datetime,
    [KouzoShukaCarId1New] int,
    [KouzoShukaDate1New] date,
    [KouzoChukeiDate1New] date,
    [KouzoShukaCarId2New] int,
    [KouzoShukaDate2New] date,
    [KouzoChukeiDate2New] date,
    [HagaraShukaCarIdNew] int,
    [HagaraShukaDateNew] date,
    [HagaraChukeiDateNew] date,
    [BikoNew] nvarchar(100),
    [KakuninhyoFilePath] nvarchar(400),
    [IDSGohanShukaDate] date,
    [IDSGohanChukeiDate] date,
    [LogiBiko] nvarchar(100),
    [Tokumei] nvarchar(2),
    [KouzoTaiou] nvarchar(5),
    [HagaraTaiou] nvarchar(5),
    [TroubleBiko] nvarchar(20),
    [NobuchiKompoDate] date,
    [NobuchiKompoYoteiDate] date,
    [NobuchiDataUketoriDate] date,
    [NobuchiStatusId] int,
    [NobuchiShukaDate] date,
    [NobuchiChukeiDate] date,
    [NobuchiBiko] nvarchar(100),
    PRIMARY KEY ([ShukaYoteiId])  
);

CREATE TABLE [dbo].[TblYotei] (
    [YoteiId] int,
    [KoteiDetailId] int,
    [ZumenUketukeDate] date,
    [KotoShoninDate] date,
    [CheckBackDate] date,
    [ShoninDate] date,
    [KakoYoteiDate] date,
    [ChinaPdfIraiDate] date,
    [ChinaPdfHenkyakuDate] date,
    [CadInputId1] int,
    [CadInputId2] int,
    [SakuzuIraiDate] date,
    [SakuzuNohinYoteiDate@] date,
    [SakuzuHenkyakuDate] date,
    [SakuzuSosinDate] date,
    [MokuzaiRiyou1] date,
    [MokuzaiRiyouBiko] nvarchar(50),
    [ChinaSakuzuTankaOfHajimeId] int,
    [ChinaSakuzuTankaId] int,
    [ChinaShiharaiInitCheck] bit,
    [ChinaShiharaiTanka] numeric(7, 0),
    [ChinaShiharaiGengakuDate] date,
    [ChinaShiharaiGengakuId] int,
    [ChinaShiharaiKingaku] numeric(7, 0),
    [ChinaShiharaiDate] date,
    [ClaimNebiki] numeric(7, 0),
    [IsMokuzaiRiyouPoint] bit,
    [IsMokuzaiRiyouPointAdd] bit,
    [Biko] nvarchar(50),
    [CadInputId1_2] int,
    [CadInputId2_2] int,
    [SakuzuIraiDate_2] date,
    [SakuzuHenkyakuDate_2] date,
    [SakuzuSosinDate_2] date,
    [ChinaSakuzuTankaId_2] int,
    [ChinaShiharaiInitCheck_2] bit,
    [ChinaShiharaiTanka_2] numeric(7, 0),
    [ChinaShiharaiGengakuDate_2] date,
    [ChinaShiharaiGengakuId_2] int,
    [ChinaShiharaiKingaku_2] numeric(7, 0),
    [ChinaShiharaiDate_2] date,
    [InsertShainId] int,
    [InsertFormName] nvarchar(50),
    [InsertDateTime] datetime,
    [UpdateShainId] int,
    [UpdateFormName] nvarchar(50),
    [UpdateDateTime] datetime,
    [KanryoKakuninDate] date,
    [KakoShoninSosinDate] date,
    [KakoShoninHenkyakuDate] date,
    [SekeiSyozoku] nvarchar(100),
    [SekeiTanto] nvarchar(100),
    [IsKanryo] bit,
    [SakuzuSekkeiJyuryoDate] date,
    [SyogoIraiSaki] nvarchar(100),
    [SyogoIraiDate] date,
    [SyogoJyuryoDate] date,
    [KakoShoninJyuryoGaichuSaki] nvarchar(100),
    [GaichuSakiSofuDate] date,
    [FinalSyoninSofuYoteiDate] date,
    [FinalSyoninSofuDate] date,
    [KanamonoJyuryoDate] date,
    [KanamonoSekisanSofuDate] date,
    [IDSCADBiko] nvarchar(100),
    [IsKanryoDate] date,
    [HagaraGaichuSousinbi] date,
    [IsSekisanId] int,
    PRIMARY KEY ([YoteiId])  
);